### ISSUE TITLE
Loot windows keep reappearing

### ISSUE THREAD

**Issue by Azzuri-UK** [evil-morfar/RCLootCouncil_Classic#57]
After we kill a boss and start a session raid members can select need/pass etc as normal but shortly after that the loot windows appear again and this happens multiple times.  If they click pass or something different to their first choice it overwrites their initial selection as well.

**Comment by evil-morfar** [comment]
I'd like to have a look at your saved variables - it's located at: `../World of Warcraft/_classic_/WTF/Account/"account_name"/SavedVariables/RCLootCouncil_Classic.lua`.

**Comment by Azzuri-UK** [comment]
of the master looter?  Will get that for you

**Comment by Azzuri-UK** [comment]
I don't know if it makes a difference but we play on a Hardcore Realm and the file was in _classic_era_ not _classic_

**Comment by Azzuri-UK** [comment]
[RCLootCouncil_Classic.lua.txt](https://github.com/user-attachments/files/16008232/RCLootCouncil_Classic.lua.txt)

**Comment by evil-morfar** [comment]
It happens because you're starting the session multiple times, and your comms are so extremely throttled that it takes a long time for the data to be sent.
Most of the throttling is due to players reconnect or otherwise receiving data out of order, causing extra data to require syncing - that's something I can change, as that sort of syncing is deprecated with Blizzards new comms throttle. That'll be implemented next update.

Until then, make sure you don't start multiple sessions (it can easily take 1 second per item or more, depending on what else is going on), and if you do feel like nothing's happening, do a `/reload` to "flush" the comms.

**Comment by Azzuri-UK** [comment]
@evil-morfar Could you do me a favour and delete this entire issue?
